version: '3'

services:
  search:
    container_name: elastic
    build:
      context: ./
      dockerfile: Dockerfile.search
    # working_dir: /app
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
  db:
    container_name: db
    image: postgres:14
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile.app
    command: python manage.py runserver 0.0.0.0:8010
    env_file:
      - ./.env
    working_dir: /app
    ports:
      - '8010:8010'
    volumes:
      - ./:/app

volumes:
  db:
  data:


